---
logs:
  level: DEBUG
  token: ~
audit_and_score_job:
    name: "eho-audit_and_score-0.1.0_test"
    appId: "eho-audit_and_score-0.1.0"
    archive: True
    maxRunTime: "01:00:00"
    archiveSystem: "data-tacc-work-eho"
    archivePath: "archive/jobs/${JOB_NAME}-${JOB_ID}"
