---
logs:
  level: DEBUG
  token: ~
mini_qc_job:
    name: "eho-qc_hikari test"
    appId: "eho-qc_hikari-0.1.0"
    archive: True
    maxRunTime: "01:00:00"
    archiveSystem: "data-tacc-work-eho"
    archivePath: "archive/jobs/${JOB_NAME}-${JOB_ID}"
    parameters:
        experiment_id: "experiment.ginkgo.19606.19637.19708.19709"
        DEBUG_preproc_max: 1
