---
logs:
  level: DEBUG
  token: ~
debug: False
downstream_callback: "https://api.sd2e.org/actors/v2/P1Vmggjk0Yg7D/messages?x-nonce=SD2E_pm77GL10QeEk3"
mini_preproc_job:
    name: "eho-mini_preproc_app test"
    appId: "eho-mini_preproc_app-0.1.0"
    archive: True
    maxRunTime: "01:00:00"
    archiveSystem: "data-tacc-work-eho"
    archivePath: "archive/jobs/audit_preproc_rx_test"
    inputs:
        fs_remote_fp: "agave://data-tacc-work-eho/data/test/status.txt"
    parameters: {}
