---
logs:
  level: DEBUG
  token: ~
mini_preproc_job:
    name: "eho-mini_preproc_app test"
    appId: "eho-mini_preproc_app-0.1.0"
    archive: True
    maxRunTime: "01:00:00"
    archiveSystem: "data-tacc-work-eho"
    archivePath: "archive/jobs/${JOB_NAME}-${JOB_ID}"
    inputs:
        dl_file: "agave://data-sd2e-community/products/v2/106bd127e2d257acb9be11ed06042e68/PAVyR8Dv1evr40LyJ52dX0DP/OZY85OoqyjJ2jZz2JAqLdR0J/sample.ginkgo.13108575.experiment.ginkgo.19606.19637.19708.19709_MG1655_NAND_Circuit_replicate_4_time_18.0:hours_temp_37.0_arabinose_0.5_mM_IPTG_0.00025_mM.rnaseq.original.bwa.flagstat.txt"
