---
logs:
  level: DEBUG
  token: ~
mini_preproc_job:
    name: "eho-mini_preproc_app test"
    appId: "eho-mini_preproc_app-0.1.0"
    archive: True
    maxRunTime: "01:00:00"
    archiveSystem: "data-tacc-work-eho"
    archivePath: "archive/jobs/${JOB_NAME}-${JOB_ID}"
