#!/bin/bash

set -e

# this is where we mount the binary directories

SORTMERNA_DIR=/opt/sortmerna-2.1b/
TRIMMOMATIC_DIR=/opt/Trimmomatic-0.36/
FASTQC_DIR=/opt/FastQC/
RNADB_CONFIG="config"
RNADB_KEY="rnadb_list"

echo this is the newest sortmerna

echo $0 $@

#out of paranoia make sure our parameters are set
if [ ${1}x = x ]; then
   echo READ1 is blank
   exit 1
fi
if [ ${2}x = x ]; then
   echo READ2 is blank
   exit 1
fi
if [ ${3}x = x ]; then
   echo TRIM is blank
   exit 1
fi
if [ ${4}x = x ]; then
   echo ADAPTER is blank
   exit 1
fi
if [ ${5}x = x ]; then
   echo MINLEN is blank
   exit 1
fi
if [ ${6}x = x ]; then
   echo SORT is blank
   exit 1
fi
if [ ${7}x = x ]; then
   echo filterseqs is blank
   exit 1
fi

# get the parameters 1 to 6 ... someday do checking

R1=${1}
R2=${2}
TRIM=${3}
ADAPTER=${4}
MINLEN=${5}
SORT=${6}
RNADB_DIR=${7}


rnadb_config=${RNADB_DIR}/${RNADB_CONFIG}

if [ ! -f $rnadb_config ] ; then
   echo "No RNADB File found called $rnadb_config"
   exit 1
fi

while IFS=" " read -r key val; do
  if [ ${key} == ${RNADB_KEY} ]; then
    RNADB=${val}
  fi
done <"$rnadb_config"

if [ ${RNADB}x == x ]; then
   echo "No $RNADB_KEY found in RNA database config file $RNADB_CONFIG"
   exit 1
else
   echo "Using RNADB of $RNADB"
fi

# get the thread count of this container
THREADS=`cat /proc/cpuinfo | grep processor | wc -l`
NTHREADS=$(($CORES - 10))
paired=1

# if we get the default R2 value of ENOSUCH, this is an unpaired run

if [ $R2 = "ENOSUCH_R2.fastq" ]; then
    paired=0
fi


FASTQ_SUFFIX=".fastq"
FQ_SUFFIX=".fq"
if [[ $R1 =~ $FQ_SUFFIX ]]; then
   R1NAME=${R1::-3}
fi
if [[ $R1 =~ $FASTQ_SUFFIX ]]; then
   R1NAME=${R1::-6}
fi
echo R1 is $R1

# do the same for R2 if we are paired

if [ $paired == 1 ]; then
    if [[ $R2 =~ $FQ_SUFFIX ]]; then
       R2NAME=${R2::-3}
    fi
    if [[ $R2 =~ $FASTQ_SUFFIX ]]; then
       R2NAME=${R2::-6}
    fi
fi
echo R2 is $R2

#R1NAME=${R1NAME%.f*}
R1NAME=${R1NAME%_001_paired}
R2NAME=${R2NAME%_001_paired}
echo RNAME1 is $R1NAME
echo RNAME2 is $R2NAME
# trim if we are told to

if [ $TRIM == 1 ]; then
    if [ $paired == 1 ]; then
       echo java -jar ${TRIMMOMATIC_DIR}/trimmomatic-0.36.jar PE -phred33 ${R1} ${R2} ${R1NAME}_trimmed.fastq ${R1NAME}_unpaired.fastq ${R2NAME}_trimmed.fastq ${R2NAME}_unpaired.fastq ILLUMINACLIP:${TRIMMOMATIC_DIR}/adapters/${ADAPTER} LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:${MINLEN}
       java -jar ${TRIMMOMATIC_DIR}/trimmomatic-0.36.jar PE -phred33 ${R1} ${R2} ${R1NAME}_trimmed.fastq ${R1NAME}_unpaired.fastq ${R2NAME}_trimmed.fastq ${R2NAME}_unpaired.fastq ILLUMINACLIP:${TRIMMOMATIC_DIR}/adapters/${ADAPTER} LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:${MINLEN}
       echo ${SORTMERNA_DIR}/scripts/merge-paired-reads.sh ${R1NAME}_trimmed.fastq ${R2NAME}_trimmed.fastq ${R1NAME}_merged-reads.fastq
       ${SORTMERNA_DIR}/scripts/merge-paired-reads.sh ${R1NAME}_trimmed.fastq ${R2NAME}_trimmed.fastq ${R1NAME}_merged-reads.fastq
       echo SORT_FILE=${R1NAME}_merged-reads.fastq
       SORT_FILE=${R1NAME}_merged-reads.fastq
    else
       echo java -jar ${TRIMMOMATIC_DIR}/trimmomatic-0.36.jar SE -phred33 ${R1} ${R1NAME}_trimmed.fastq ILLUMINACLIP:${TRIMMOMATIC_DIR}/adapters/${ADAPTER} LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:${MINLEN}
       java -jar ${TRIMMOMATIC_DIR}/trimmomatic-0.36.jar SE -phred33 ${R1} ${R1NAME}_trimmed.fastq ILLUMINACLIP:${TRIMMOMATIC_DIR}/adapters/${ADAPTER} LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:${MINLEN}
       echo SORT_FILE=${R1NAME}_trimmed.fastq
       SORT_FILE=${R1NAME}_trimmed.fastq
    fi
else
  echo "Skipping TRIMOMATIC step based on users request"
fi

# sort if we are told to
echo "checking sortmerna"
if [ $SORT == 1 ]; then
    rsync -rltv $RNADB_DIR ./
    RNADB_DIR=$(basename $RNADB_DIR)
    gunzip $RNADB_DIR/*.gz
    if [ $paired == 1 ]; then
    echo ${SORTMERNA_DIR}/sortmerna --paired_out --ref ${RNADB}  --reads ${SORT_FILE} --num_alignments 1 --fastx --aligned ${R1NAME}_rRNA --other ${R1NAME}_rRNA_free_reads -a $NTHREADS --log -v --blast 1
    ${SORTMERNA_DIR}/sortmerna --paired_out --ref ${RNADB}  --reads ${SORT_FILE} --num_alignments 1 --fastx --aligned ${R1NAME}_rRNA --other ${R1NAME}_rRNA_free_reads -a $NTHREADS --log -v --blast 1
    echo ${SORTMERNA_DIR}/scripts/unmerge-paired-reads.sh ${R1NAME}_rRNA_free_reads.fastq X${R1NAME}_rRNA_free_reads.fastq ${R2NAME}_rRNA_free_reads.fastq
    ${SORTMERNA_DIR}/scripts/unmerge-paired-reads.sh ${R1NAME}_rRNA_free_reads.fastq X${R1NAME}_rRNA_free_reads.fastq ${R2NAME}_rRNA_free_reads.fastq
    echo mv X${R1NAME}_rRNA_free_reads.fastq ${R1NAME}_rRNA_free_reads.fastq
    mv X${R1NAME}_rRNA_free_reads.fastq ${R1NAME}_rRNA_free_reads.fastq
    else
        echo ${SORTMERNA_DIR}/sortmerna --ref ${RNADB}  --reads ${SORT_FILE} --num_alignments 1 --fastx --aligned ${R1NAME}_rRNA --other ${R1NAME}_rRNA_free_reads -a $NTHREADS --log -v --blast 1
        ${SORTMERNA_DIR}/sortmerna --ref ${RNADB}  --reads ${SORT_FILE} --num_alignments 1 --fastx --aligned ${R1NAME}_rRNA --other ${R1NAME}_rRNA_free_reads -a $NTHREADS --log -v --blast 1
    fi
else
  echo "Skipping SORTMERNA step based on users request"
fi

# gzip the trimmed inputs


if [ $TRIM == 1 ]; then
    if [ $paired == 1 ]; then
        ${FASTQC_DIR}/fastqc ${R1NAME}_trimmed.fastq &
        ${FASTQC_DIR}/fastqc ${R2NAME}_trimmed.fastq &
        wait
        gzip ${R1NAME}_trimmed.fastq &
        gzip ${R2NAME}_trimmed.fastq &
        wait
        if [ $SORT == 1 ]; then
           ${FASTQC_DIR}/fastqc ${R1NAME}_rRNA_free_reads.fastq &
           ${FASTQC_DIR}/fastqc ${R2NAME}_rRNA_free_reads.fastq &
           wait
           gzip ${R1NAME}_rRNA_free_reads.fastq &
           gzip ${R2NAME}_rRNA_free_reads.fastq &
           wait
        fi
    else
        ${FASTQC_DIR}/fastqc ${R1NAME}_trimmed.fastq
        gzip ${R1NAME}_trimmed.fastq
        if [ $SORT == 1 ]; then
          ${FASTQC_DIR}/fastqc ${R1NAME}_rRNA_free_reads.fastq
          gzip ${R1NAME}_rRNA_free_reads.fastq
        fi
    fi
    echo done with all gzips
fi


# report out and clean up...

echo "R1 reads removed by Trimmomatic: "
echo $(cat ${R1NAME}_unpaired.fastq|wc -l)/4|bc
echo "R2 reads removed by Trimmomatic: "
echo $(cat ${R2NAME}_unpaired.fastq|wc -l)/4|bc
echo "Reads removed by SortmeRNA: "
echo $(cat ${R1NAME}_rRNA.fastq|wc -l)/4|bc


rm -rf $(basename $RNADB_DIR)
rm -f *_unpaired.fastq
rm -f *_rRNA.fastq
rm -f *_rRNA.blast
rm -f *_merged-reads.fastq
rm -f *unpaired.fastq
